package com.pv207.pv207_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Bug implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BUG_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "BUG_ID_SEQ", name = "BUG_ID_GENERATOR")
    private java.lang.Long id;

    public Bug() {
    }
    
    public Bug(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}