package com.pv207.pv207_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Feedback implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Feedback() {
    }




}